services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      retries: 5

  app:
    build:    
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: dbname
      PORT: :3001
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://user:password@db:5432/dbname?sslmode=disable"
      DB_CONFIG: postgres://user:password@db:5432/dbname?sslmode=disable
    ports:
      - "3001:3001"
volumes:
  db-data: {}  # default 'local' driver

