export const Descriptions = {
  Income: [
    "Salary/Paycheck",
    "Freelance Income",
    "Rental Income",
    "Dividend Payments",
    "Interest Income",
    "Bonus",
    "Sales Revenue",
    "Investment Returns",
    "Government Benefits",
    "Reimbursements",
  ],
  Expense: [
    "Groceries",
    "Rent/Mortgage Payment",
    "Utilities",
    "Transportation",
    "Dining Out/Restaurants",
    "Shopping/Retail Purchases",
    "Subscription Services",
    "Insurance",
    "Travel/Vacation Expenses",
    "Medical Bills",
    "Education/Tuition Fees",
    "Loan Repayments",
    "Taxes",
  ],
}
